// 직종 카테고리
export enum Profession {
  DEVELOPER = 'DEVELOPER', // 개발자
  DESIGNER = 'DESIGNER', // 디자이너 (UI/UX, 그래픽 등)
  PM = 'PM', // 프로덕트 매니저
  MARKETER = 'MARKETER', // 마케터
  DATA_ANALYST = 'DATA_ANALYST', // 데이터 분석가
  CONTENT_CREATOR = 'CONTENT_CREATOR', // 콘텐츠 크리에이터
  WRITER = 'WRITER', // 작가/카피라이터
  PHOTOGRAPHER = 'PHOTOGRAPHER', // 사진작가
  VIDEO_CREATOR = 'VIDEO_CREATOR', // 영상 제작자
  MUSICIAN = 'MUSICIAN', // 음악가/작곡가
  PLANNER = 'PLANNER', // 기획자
  RESEARCHER = 'RESEARCHER', // 연구원
  CONSULTANT = 'CONSULTANT', // 컨설턴트
  EDUCATOR = 'EDUCATOR', // 교육자
  OTHER = 'OTHER', // 기타
}

// 프로젝트 카테고리
export enum ProjectCategory {
  WEB_APP = 'WEB_APP', // 웹 애플리케이션
  MOBILE_APP = 'MOBILE_APP', // 모바일 앱
  DESIGN = 'DESIGN', // 디자인 작업물
  BRANDING = 'BRANDING', // 브랜딩/아이덴티티
  MARKETING = 'MARKETING', // 마케팅 캠페인
  VIDEO = 'VIDEO', // 영상 콘텐츠
  PHOTOGRAPHY = 'PHOTOGRAPHY', // 사진 작업물
  MUSIC = 'MUSIC', // 음악/오디오
  WRITING = 'WRITING', // 글/콘텐츠
  RESEARCH = 'RESEARCH', // 연구/논문
  DATA_ANALYSIS = 'DATA_ANALYSIS', // 데이터 분석
  CASE_STUDY = 'CASE_STUDY', // 케이스 스터디
  PRESENTATION = 'PRESENTATION', // 프레젠테이션
  GAME = 'GAME', // 게임
  HARDWARE = 'HARDWARE', // 하드웨어/IoT
  OTHER = 'OTHER', // 기타
}

// 협업 상태
export enum CollaborationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
}

// 직종별 라벨 (UI 표시용)
export const ProfessionLabels: Record<Profession, string> = {
  [Profession.DEVELOPER]: '개발자',
  [Profession.DESIGNER]: '디자이너',
  [Profession.PM]: '프로덕트 매니저',
  [Profession.MARKETER]: '마케터',
  [Profession.DATA_ANALYST]: '데이터 분석가',
  [Profession.CONTENT_CREATOR]: '콘텐츠 크리에이터',
  [Profession.WRITER]: '작가/카피라이터',
  [Profession.PHOTOGRAPHER]: '사진작가',
  [Profession.VIDEO_CREATOR]: '영상 제작자',
  [Profession.MUSICIAN]: '음악가/작곡가',
  [Profession.PLANNER]: '기획자',
  [Profession.RESEARCHER]: '연구원',
  [Profession.CONSULTANT]: '컨설턴트',
  [Profession.EDUCATOR]: '교육자',
  [Profession.OTHER]: '기타',
};

// 프로젝트 카테고리별 라벨 (UI 표시용)
export const ProjectCategoryLabels: Record<ProjectCategory, string> = {
  [ProjectCategory.WEB_APP]: '웹 애플리케이션',
  [ProjectCategory.MOBILE_APP]: '모바일 앱',
  [ProjectCategory.DESIGN]: '디자인',
  [ProjectCategory.BRANDING]: '브랜딩',
  [ProjectCategory.MARKETING]: '마케팅 캠페인',
  [ProjectCategory.VIDEO]: '영상',
  [ProjectCategory.PHOTOGRAPHY]: '사진',
  [ProjectCategory.MUSIC]: '음악/오디오',
  [ProjectCategory.WRITING]: '글/콘텐츠',
  [ProjectCategory.RESEARCH]: '연구/논문',
  [ProjectCategory.DATA_ANALYSIS]: '데이터 분석',
  [ProjectCategory.CASE_STUDY]: '케이스 스터디',
  [ProjectCategory.PRESENTATION]: '프레젠테이션',
  [ProjectCategory.GAME]: '게임',
  [ProjectCategory.HARDWARE]: '하드웨어/IoT',
  [ProjectCategory.OTHER]: '기타',
};

// 직종별 추천 스킬 목록
export const SuggestedSkillsByProfession: Record<Profession, string[]> = {
  [Profession.DEVELOPER]: [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'Go',
    'Rust',
    'C++',
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'Node.js',
    'Django',
    'Spring',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Git',
    'CI/CD',
    'TDD',
    'Agile',
    'REST API',
    'GraphQL',
  ],
  [Profession.DESIGNER]: [
    'Figma',
    'Sketch',
    'Adobe XD',
    'Photoshop',
    'Illustrator',
    'After Effects',
    'InVision',
    'Principle',
    'Framer',
    'Zeplin',
    'Abstract',
    'UI Design',
    'UX Design',
    'Interaction Design',
    'Visual Design',
    'Design System',
    'Prototyping',
    'User Research',
    'Wireframing',
  ],
  [Profession.PM]: [
    'Jira',
    'Asana',
    'Trello',
    'Notion',
    'Confluence',
    'Monday.com',
    'Figma',
    'Miro',
    'Lucidchart',
    'Google Analytics',
    'Mixpanel',
    'Amplitude',
    'PRD 작성',
    'User Story',
    'A/B Testing',
    'KPI 설정',
    'Roadmap 관리',
    'Agile',
    'Scrum',
    'Kanban',
    'OKR',
  ],
  [Profession.MARKETER]: [
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Instagram Ads',
    'SEO',
    'SEM',
    'Content Marketing',
    'Email Marketing',
    'CRM',
    'HubSpot',
    'Mailchimp',
    'Hootsuite',
    'Buffer',
    'Copywriting',
    'A/B Testing',
    'Growth Hacking',
    'Brand Strategy',
  ],
  [Profession.DATA_ANALYST]: [
    'Python',
    'R',
    'SQL',
    'Excel',
    'Tableau',
    'Power BI',
    'Looker',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'TensorFlow',
    'PyTorch',
    'Statistics',
    'Machine Learning',
    'Data Visualization',
    'ETL',
    'BigQuery',
    'Snowflake',
    'Apache Spark',
  ],
  [Profession.CONTENT_CREATOR]: [
    'YouTube',
    'Instagram',
    'TikTok',
    'Twitter',
    'Blog',
    'Premiere Pro',
    'Final Cut Pro',
    'DaVinci Resolve',
    'Photoshop',
    'Lightroom',
    'Canva',
    'Storytelling',
    'Video Editing',
    'Photography',
    'Copywriting',
  ],
  [Profession.WRITER]: [
    'Google Docs',
    'Notion',
    'Medium',
    'WordPress',
    'Ghost',
    'Copywriting',
    'Technical Writing',
    'Creative Writing',
    'SEO Writing',
    'Editing',
    'Proofreading',
    'Research',
    'Storytelling',
    'Grammarly',
    'Hemingway Editor',
  ],
  [Profession.PHOTOGRAPHER]: [
    'Lightroom',
    'Photoshop',
    'Capture One',
    'DxO PhotoLab',
    'Portrait',
    'Landscape',
    'Product',
    'Event',
    'Street',
    'Studio Lighting',
    'Natural Light',
    'Post-processing',
    'Canon',
    'Nikon',
    'Sony',
    'Fujifilm',
  ],
  [Profession.VIDEO_CREATOR]: [
    'Premiere Pro',
    'Final Cut Pro',
    'DaVinci Resolve',
    'After Effects',
    'Cinema 4D',
    'Blender',
    'Motion Graphics',
    'Color Grading',
    'Sound Design',
    'Scriptwriting',
    'Storyboarding',
    'Documentary',
    'Commercial',
    'Music Video',
    'Short Film',
  ],
  [Profession.MUSICIAN]: [
    'Ableton Live',
    'Logic Pro',
    'FL Studio',
    'Pro Tools',
    'Cubase',
    'Music Theory',
    'Composition',
    'Arrangement',
    'Mixing',
    'Mastering',
    'Piano',
    'Guitar',
    'Drums',
    'Bass',
    'Vocals',
    'Synthesizer',
    'Sound Design',
    'Film Scoring',
    'Song Production',
  ],
  [Profession.PLANNER]: [
    'PowerPoint',
    'Keynote',
    'Google Slides',
    'Notion',
    'Confluence',
    'Excel',
    'Google Sheets',
    'Miro',
    'Lucidchart',
    'Strategic Planning',
    'Business Analysis',
    'Market Research',
    'Proposal Writing',
    'Presentation',
    'Stakeholder Management',
  ],
  [Profession.RESEARCHER]: [
    'SPSS',
    'R',
    'Python',
    'Stata',
    'NVivo',
    'ATLAS.ti',
    'Quantitative Research',
    'Qualitative Research',
    'Survey Design',
    'Statistical Analysis',
    'Data Collection',
    'Literature Review',
    'Academic Writing',
    'Peer Review',
    'Grant Writing',
  ],
  [Profession.CONSULTANT]: [
    'PowerPoint',
    'Excel',
    'Tableau',
    'Think-Cell',
    'Strategy',
    'Business Analysis',
    'Financial Modeling',
    'Market Analysis',
    'Due Diligence',
    'Change Management',
    'Stakeholder Management',
    'Presentation',
    'Problem Solving',
  ],
  [Profession.EDUCATOR]: [
    'Curriculum Design',
    'Lesson Planning',
    'Assessment Design',
    'Google Classroom',
    'Canvas',
    'Moodle',
    'Zoom',
    'Teams',
    'Public Speaking',
    'Mentoring',
    'Workshop Facilitation',
    'E-learning',
    'Instructional Design',
    'Educational Technology',
  ],
  [Profession.OTHER]: [
    'Communication',
    'Problem Solving',
    'Critical Thinking',
    'Time Management',
    'Leadership',
    'Teamwork',
    'Adaptability',
    'Microsoft Office',
    'Google Workspace',
    'Slack',
    'Zoom',
  ],
};
